### ISSUE TITLE
adding flag or changing mode breaks reset axes button

### ISSUE THREAD

**Issue by Sam5M** [epic-astronomy/waterfalls#1]
After zooming into a spectrogram, if you change the polarization mode or add a flag, the reset axes button stops you from zooming out, even after removing the flag.

**Comment by infinitron** [comment]
The reset button tries to go to the previous zoom level instead of zooming out. Let me check Plotly's documentation to see if this is the intended behavior. But double-clicking on the plot resets the axes as expected.

**Comment by Sam5M** [comment]
Thanks for looking into it!
